#!/usr/bin/env bash
set -eu

apt install npm -y
python3 -m venv xkcd-pass-venv
if [ -d xkcd-pass-venv/bin ]; then
	source xkcd-pass-venv/bin/activate
fi
cd "$(dirname "$0")"
pip3 install build
pip3 install wheel
pip3 install -r ../../requirements.txt
./install-shellcheck
./install-shfmt
npm install
