#!/usr/bin/env python3
from __future__ import print_function
from __future__ import absolute_import

import argparse

from zulint.linters import run_pyflakes
from zulint.command import add_default_linter_arguments, LinterConfig
from zulint.custom_rules import RuleList

MYPY = False
if MYPY:
    from typing import List, Tuple

def run():
    # type: () -> None
    parser = argparse.ArgumentParser()
    # Add custom parser arguments here.

    add_default_linter_arguments(parser)
    args = parser.parse_args()

    linter_config = LinterConfig(args)

    # Linters will be run on these file types.
    # eg: file_types = ['py', 'html', 'css', 'js']
    file_types = ['py']

    EXCLUDED_FILES = [
        # No linters will be run on files in this list.
        # eg: 'path/to/file.py'
    ]  # type: List[str]
    by_lang = linter_config.list_files(file_types, exclude=EXCLUDED_FILES)

    command = ["tools/run-mypy", "--quiet"]

    linter_config.external_linter('mypy', command, ['py'], pass_targets=False,
                                  description="Static type checker for Python")

    linter_config.external_linter(
        "gitlint",
        ["tools/commit-message-lint"],
        description="Checks commit messages for common formatting errors (config: .gitlint)",
    )

    linter_config.external_linter(
        "isort",
        ["isort"],
        ["py"],
        description="Sorts Python import statements",
        check_arg=["--check-only", "--diff"],
    )

    @linter_config.lint
    def check_custom_rules():
        # type: () -> int
        """Check trailing whitespace for specified files"""
        trailing_whitespace_rule = RuleList(
            langs=file_types,
            rules=[{
                'pattern': r'\s+$',
                'strip': '\n',
                'description': 'Fix trailing whitespace'
            }]
        )
        failed = trailing_whitespace_rule.check(by_lang, verbose=args.verbose)
        return 1 if failed else 0

    @linter_config.lint
    def pyflakes():
        # type: () -> int
        suppress_patterns = [
            # Error patters in this list will be will not be reported by the linter.
            # syntax: ('File Path', 'Error message')
            # eg: ('path/to/file.py', 'imported but unused')
        ]  # type: List[Tuple[str, str]]
        failed = run_pyflakes(by_lang['py'], args, suppress_patterns)
        return 1 if failed else 0

    linter_config.do_lint()

if __name__ == '__main__':
    run()