name: Build xkcd-pass

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test and build xkcd-pass
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup non-python dependencies.
      run: |
        sudo tools/setup/install-shellcheck
        sudo tools/setup/install-shfmt
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
    - name: Run unittests
      run: |
        PYTHONPATH=src pytest
    - name: Run linters.
      run: |
        ./tools/lint
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .