name: Build xkcd_pass

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test and build xkcd_pass
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Run unittests
      run: |
        pip install pytest
        PYTHONPATH=src pytest
    - name: Run linters.
      run: |
        ./tools/lint
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .